# Generated by Django 5.1.3 on 2024-12-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_and_news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pawpost',
            name='rating',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
