# Generated by Django 5.1.3 on 2024-12-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_and_news', '0002_remove_pawpost_rating_delete_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='pawpost',
            name='additional_mentions',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pawpost',
            name='image',
            field=models.ImageField(upload_to='profile_pics/pawposts/'),
        ),
    ]
