# Generated by Django 5.0.6 on 2024-12-17 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_and_news', '0003_pawpost_additional_mentions_alter_pawpost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pawpost',
            name='author',
        ),
    ]
