# Generated by Django 5.0.6 on 2024-11-30 12:08

import django.core.validators
import django.db.models.deletion
import core.validators as validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(8, message="The pet hotel's name must consist of at least 8 letters!"), validators.pet_hotel_and_shelter_name_validator])),
                ('city', models.CharField(max_length=12)),
                ('street', models.CharField(max_length=30)),
                ('street_number', models.PositiveSmallIntegerField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('favourite', models.BooleanField()),
                ('to_visit', models.BooleanField(verbose_name='to-visit')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='pets.pet')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='facilities.pethotel')),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_section', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat')])),
                ('pethotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelters', to='facilities.pethotel')),
            ],
        ),
    ]
