# Generated by Django 5.1.3 on 2024-12-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_delete_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='pethotel',
            name='outside_view',
            field=models.URLField(default='Pet Oasis'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pethotel',
            name='favourite',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pethotel',
            name='to_visit',
            field=models.BooleanField(blank=True, null=True, verbose_name='to-visit'),
        ),
    ]
