# Generated by Django 5.0.6 on 2024-12-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_pethotel_outside_view_alter_pethotel_favourite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pethotel',
            name='outside_view',
            field=models.ImageField(blank=True, null=True, upload_to='facilities/'),
        ),
    ]
