# Generated by Django 5.0.6 on 2024-12-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_alter_pethotel_outside_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pethotel',
            name='outside_view',
            field=models.URLField(),
        ),
    ]
