# Generated by Django 5.0.6 on 2024-12-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_alter_pethotel_name_alter_pethotel_outside_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pethotel',
            name='city',
            field=models.CharField(max_length=30),
        ),
    ]
