# Generated by Django 5.1.3 on 2024-12-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_pet_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/pets/'),
        ),
    ]
